### PR TITLE
Resolve checkout display issues on Magento2.3.

### PR DESCRIPTION
**Pull request by stooit**
Will resolve https://github.com/danslo/CleanCheckout/issues/77

I haven't run into any other issues in Mage2.3.

### CODE REVIEW

**Comment by Amadeco** [comment]
Good evening,

Same here on a update from 2.2.7 to 2.3.0 version.

**Comment by SimonPrins** [comment]
I have the same issue with Magento2.3 and this does fix it for me. When can we expect this PR to be merged?

**Comment by haelbichalex** [comment]
#2 should be merged instead

**Comment by edward-simpson** [comment]
Hi all,

This is fixed in #2 , which has now been merged and released

**Pull request closed without merging**
